Combine frigate job into ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -10,8 +10,6 @@ jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
-      - name: Cleanup node
-        uses: AutoModality/action-clean@1.1.0
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -24,8 +22,6 @@ jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - name: Cleanup node
-        uses: AutoModality/action-clean@1.1.0
       - name: Checkout
         uses: actions/checkout@v2
         with:
@@ -40,3 +36,33 @@ jobs:
         uses: helm/kind-action@v1.2.0
       - name: Install charts
         run: ct install --charts=charts/trino
+
+  docs:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+      - name: Install Frigate
+        run: pip install frigate
+      - name: Check if chart README is in-sync
+        run: |
+          frigate gen charts/trino > charts/trino/README.md
+          if ! git diff --exit-code --quiet; then
+            cat << 'EOF'
+          charts/trino/README.md is not in sync with chart
+          Please update charts/trino/README.md by running:
+              python3 -m venv .venv && . .venv/bin/activate
+              pip install frigate
+              frigate gen charts/trino > charts/trino/README.md
+
+          Here's a diff of what's changed:
+          EOF
+
+            git diff
+            # fail the job
+            exit 1
+          else
+            echo "charts/trino/README.md is in-sync with chart"
+          fi
